#!/usr/bin/env python
'''
Usage: djdns [ options ]

DJDNS Hosting Script

For security, this script uses privelege dropping to host on port 53 without
running as root during regular operation. You start the script as root, and
provide it with a user and group to drop to. Make sure these are allowed to
read the data files in DIR.

Options:
    -h --help  Show this message
    -d DIR     Root directory for domain information [default: .]
    -r ROOT    Path to root.json (relative to DIR)   [default: root.json]
    -p PORT    Port to host on [default: 53]
    -H HOST    Hostname to host on [default: ::]
    -u USER    User to run as during regular operation  [default: nobody]
    -g GROUP   Group to run as during regular operation [default: nogroup]
    -v         Verbose output
'''

from __future__ import print_function

from docopt import docopt
import os
import grp
import pwd
import threading
import time
import traceback
from setproctitle import setproctitle

from djdns.server import DJServer

def get_uid(username):
    return pwd.getpwnam(username).pw_uid

def get_gid(groupname):
    return grp.getgrnam(groupname).gr_gid

def drop_priveleges(user, group):
    uid = get_uid(user)
    gid = get_gid(group)
    os.setgid(gid)
    os.setuid(uid)

def serve_threaded(server):
    thread = threading.Thread(target=server.serve)
    thread.daemon = True
    thread.start()
    return thread

def serve_wait(*servers):
    try:
        while True:
            time.sleep(1)
            for server in servers:
                if not server.serving:
                    break
    except KeyboardInterrupt:
        pass

    for server in servers:
        print("STOPPING SERVER", server)
        server.stop()
        server.thread.join(1)

def main(argv):
    setproctitle('djdns')
    argv[0] = 'djdns' # Insulate against docopt being silly
    print(argv)
    arguments = docopt(__doc__, argv=argv, version='0.0.1')
    os.chdir(arguments['-d'])

    host = arguments['-h']
    if ':' in host: #IPv6
        host = (host, 0, 1)

    port = int(arguments['-p'])

    config = {
        'listen_host': host,
        'listen_port': port,
        'path'  : arguments['-r'],
        'debug' : arguments['-v'],
    }

    server = DJServer(**config)
    server.bind()
    try:
        drop_priveleges(arguments['-u'], arguments['-g'])
    except:
        traceback.print_exc()
        quit(1)

    server.thread = serve_threaded(server)
    serve_wait(server)

if __name__ == '__main__':
    import sys
    main(sys.argv)
