#!/bin/sh
### BEGIN INIT INFO
# Provides:          djdns
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DJDNS server
# Description:       Runs DJDNS with the config params in the RC script
#### END INIT INFO

NAME=djdns
USER=djdns
VENV_DIR="/var/dns/venv" # Set to "" for global installation
DATA_DIR="/var/dns/data" # Root directory of DJDNS pages
CMD="djdns"
CMD_ARGS="-d $DATA_DIR -u $USER -g $USER"

########## Common
PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
SSD=start-stop-daemon
PID=/var/run/${NAME}.pid

start () {
    echo -n "Start $NAME"
    test -d "$VENV_DIR" && . "$VENV_DIR/bin/activate"
    CMD=`which $CMD`
    $SSD --start --pidfile $PID --make-pidfile --background --exec $CMD -- $CMD_ARGS
    RETVAL=$?
    echo
    return $RETVAL
}

stop () {
    echo -n "Stop $NAME"
    $SSD --stop --oknodo --pidfile $PID
    RETVAL=$?
    echo
    return $RETVAL
}

restart () {
    stop
    sleep 1
    start
}

case "$1" in
start)
    start
    ;;

stop)
    stop
    ;;

status)
    $SSD --status --pidfile  $PID
    ;;

restart)
    restart
    ;;

*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $RETVAL
